# Obviously :)
language: java

# Be ready for the future
jdk:
  - openjdk11

# Only do other on PRs
branches:
  only:
  - master

# Seems reasonable
cache:
  directories:
    - $HOME/.m2

# Find latest release trains:
# https://spring.io/projects/spring-data#learn
matrix:
  include:
    # Supported combinations
    - name: "Boot 2.1 default combination OGM 3.1 / Lovelace"
      env:
      - SPRING_BOOT_VERSION=2.1
      - NEO4J_OGM_VERSION=3.1.15
      - SPRING_DATA_RELEASE_TRAIN_VERSION=Lovelace-SR12
    - name: "Boot 2.2 default combination OGM 3.2 / Moore"
      env: 
      - SPRING_BOOT_VERSION=2.2
      - NEO4J_OGM_VERSION=3.2.2
      - SPRING_DATA_RELEASE_TRAIN_VERSION=Moore-SR1
    # Would be nice to have it
    - name: "Boot 2.1 OGM 3.2 / Lovelace"
      env: 
      - SPRING_BOOT_VERSION=2.1
      - NEO4J_OGM_VERSION=3.2.2
      - SPRING_DATA_RELEASE_TRAIN_VERSION=Lovelace-SR12
    - name: "Boot 2.2 OGM 3.1 / Moore"
      env:
      - SPRING_BOOT_VERSION=2.2
      - NEO4J_OGM_VERSION=3.1.15
      - SPRING_DATA_RELEASE_TRAIN_VERSION=Moore-SR1

# Clone latest neo4j-ogm, assume it builds and install local snapshot
# before_script:
#  - git clone https://github.com/neo4j/neo4j-ogm;
#  - ./mvnw -f neo4j-ogm/pom.xml -Djacoco.skip=true -Dmaven.javadoc.skip=true -Dcheckstyle.skip -DskipTests=true clean install;

# Execute it
script:
  - "./mvnw -f spring-boot-${SPRING_BOOT_VERSION}/pom.xml -Dneo4j-ogm.version=${NEO4J_OGM_VERSION} -Dspring-data-releasetrain.version=${SPRING_DATA_RELEASE_TRAIN_VERSION} clean verify"
